app.config.path.files=resources/data/
app.config.path.file.name.parametros.xml=param_config.xml
app.config.path.file.name.txt=transaction.txt
app.config.path.file.name.json=transaction.json
app.config.path.file.name.csv=transaction.csv

